version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: docker
  directory: /runner
  schedule:
    interval: weekly
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
